### ISSUE TITLE
Can you cut a release?

### ISSUE THREAD

**Issue by jchodera** [jhprinz/ipynb-test#5]
We appear to [have a package on the `omnia` channel](https://anaconda.org/omnia/ipynbtest/files), but there are no official releases cut. Can you cut one so that we can include this in the standard omnia packaging channels?

**Comment by jchodera** [comment]
cc: https://github.com/omnia-md/conda-recipes/pull/630

**Comment by jchodera** [comment]
Looks like there is something non py 3.x compliant in the tests that is causing it to not find the example notebook:

```
Traceback (most recent call last):
  File "C:\Miniconda3\Scripts\conda-build-script.py", line 5, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "C:\Miniconda3\lib\site-packages\conda_build\cli\main_build.py", line 239, in main
    execute(sys.argv[1:])
  File "C:\Miniconda3\lib\site-packages\conda_build\cli\main_build.py", line 231, in execute
    already_built=None, config=config)
  File "C:\Miniconda3\lib\site-packages\conda_build\api.py", line 83, in build
    need_source_download=need_source_download, config=config)
  File "C:\Miniconda3\lib\site-packages\conda_build\build.py", line 1000, in build_tree
    test(metadata, config=recipe_config)
  File "C:\Miniconda3\lib\site-packages\conda_build\build.py", line 818, in test
    create_files(tmp_dir, m, config)
  File "C:\Miniconda3\lib\site-packages\conda_build\create_test.py", line 53, in create_files
    copy_into(path, join(dir_path, fn), config.timeout)
  File "C:\Miniconda3\lib\site-packages\conda_build\utils.py", line 112, in copy_into
    shutil.copy2(src, dst_fn)
  File "C:\Miniconda3\lib\shutil.py", line 245, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Miniconda3\lib\shutil.py", line 108, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\projects\\conda-recipes\\ipynbtest\\../../examples/ipynbtest_tutorial.ipynb'
```

**Comment by jhprinz** [comment]
On it. Will see if I can make it run on Py3.

**Comment by jchodera** [comment]
Thanks!

Alternatively, there may be a different tool that has emerged in the
meantime, like this one

https://pypi.python.org/pypi/pytest-ipynb

**Comment by jhprinz** [comment]
Yeah. I saw that. Has a little different approach. Might be worth a look. In the meantime I added Python3 support and updated travis to check for all Python versions. If not so difficult, could you add it to the nightly builds?

**Comment by jchodera** [comment]
I don't think I can easily add and maintain nightly builds, but I am happy to build a working version for `omnia` if you cut a release.

**Comment by dwhswenson** [comment]
@jhprinz : If you want nightly builds, you can set them up at http://nightli.es. I have this for my OPSPiggybackers and for all the dynamiq-md projects.

**Comment by jhprinz** [comment]
Been a while... But done... Also it supports py3.6 now.
